### ISSUE TITLE
Compile error when following instructions in readme.md

### ISSUE THREAD

**Issue by SongRb** [Faldict/sjtuxiangxiang#2]
![snipaste_20170509_180048](https://cloud.githubusercontent.com/assets/15308237/25845752/a0fae48a-34e1-11e7-9a2b-3245d5af45a4.png)

**Comment by Faldict** [comment]
I'm sorry that I haven't update the README file, and our code has changed much. 
You haven't seen the `build failed` badge?

**Comment by Faldict** [comment]
I have fixed your question, so I'll close this issue. If you still have any questions, contact me with wechat or  email.
